
- name: Remove all nodes in state NotReady after waitung 60 seconds
  ansible.builtin.shell:
    cmd: (kubectl get nodes|grep -q NotReady && sleep 60 && for node in $(kubectl get nodes|awk '$2=="NotReady" {print $1}') ; do kubectl delete node $node ; done) || echo Nothing to do
  become: true
  ignore_errors: yes

